# ACME Insurance Telematics Generator Configuration Template
# Copy this file to application.yml and customize as needed

# Server Configuration
server:
  port: 8082

# Spring Configuration
spring:
  application:
    name: imc-telematics-gen
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  profiles:
    active: local

# Telematics Simulation Configuration
telematics:
  exchange:
    name: telematics_exchange
  simulation:
    interval-ms: 50           # High-volume demo (20 messages/second)
    driver-count: 3           # Legacy (random mode). Use max-drivers to cap file-based drivers
    crash-frequency: 500       # Messages between crash events per driver
    min-crash-gforce: 6.0     # Enforce minimum G-force for forced crashes
    max-drivers: 15           # Cap number of drivers initialized from drivers.json (0 = no cap)
  
  # Driver Behavior Configuration
  behavior:
    post-crash-idle-minutes: 15      # Time drivers sit idle after crash
    random-stop-probability: 0.05    # Probability of random stops (5%)
    break-duration-minutes: 5        # Duration of break stops
    
    # Time-based Activity Configuration
    night-start-hour: 20             # Hour when night activity begins (8 PM)
    night-end-hour: 6                # Hour when night activity ends (6 AM)
    night-driving-reduction: 0.5     # Reduce driving probability by 70% at night
    night-parked-probability: 0.85   # 85% chance drivers stay parked at night
    peak-hours: [7, 10, 15, 19]       # Rush hour times (7-8 AM, 5-6 PM)
    peak-driving-boost: 2          # Increase driving activity 50% during peak hours
  
  # Location Configuration (Atlanta center)
  location:
    latitude: 33.7490         # Atlanta center latitude
    longitude: -84.3880       # Atlanta center longitude
  
  # Policy Configuration
  policy:
    id: IMC-AUTO-98765  # Base policy ID (actual IDs are generated as IMC-98675, IMC-98680, etc.)

# Logging Configuration
logging:
  level:
    com.insurancemegacorp.telematicsgen: INFO
    org.springframework.amqp: WARN
    org.springframework.web.socket: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,shutdown
      cors:
        allowed-origin-patterns: "*"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true